steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/hello-world-repo/hello-world'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'us-docker.pkg.dev/$PROJECT_ID/hello-world-repo/hello-world'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - hello-world
      - '--image=us-docker.pkg.dev/$PROJECT_ID/hello-world-repo/hello-world'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
